### ISSUE TITLE
Client Logo's section(Home page) : Image/logo should resize as per the aspect ratio

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Castleglen#32]
![philippine food and toiletry products wholesaler - perth wa - castleglen enterprises - the widest range of philippine products at the best price to consumers 2016-01-06 10-06-16](https://cloud.githubusercontent.com/assets/13309806/12135156/7d2489ca-b3ec-11e5-83d1-db8d3c39732f.png)

**Comment by Santosh-titan** [comment]
We should not hard crop the logo that's why its not cropped as per the aspect ratio. If the logo image is smaller than actual ratio, than it should aligned center (vertically and horizontally) .
