### ISSUE TITLE
Banner: Clipped banner text.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Castleglen#37]
![image](https://cloud.githubusercontent.com/assets/11186313/12287809/611af092-ba0a-11e5-9f3b-c8259b968039.png)

**Comment by Santosh-titan** [comment]
I tested this in browser re-flow, for me its working fine.

**Comment by roseliesromeo** [comment]
Still clipped using Chrome.
![image](https://cloud.githubusercontent.com/assets/11186313/12571247/39c6c0ce-c41a-11e5-975c-59d57196a6f3.png)
