### ISSUE TITLE
Home: Background image stretches when content is expanded.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Castleglen#40]

**Comment by Santosh-titan** [comment]
when content is expanded background image will also expand, So obviously it will stretch the image.

**Comment by roseliesromeo** [comment]
We still can do something about it. You can refer to this site.
http://clevercreatures.stage.titanweb.com.au/

**Comment by roseliesromeo** [comment]
It looks good already.  But I can see fold in the background.  Can we smoothen it or blend the edges?
![image](https://cloud.githubusercontent.com/assets/11186313/12634312/4dd9c3c8-c5b3-11e5-9aa9-9cefa3d9ea00.png)

**Comment by roseliesromeo** [comment]
Not fixed.
![image](https://cloud.githubusercontent.com/assets/11186313/12711098/fba93212-c8f7-11e5-9983-00170c0a97e6.png)
![image](https://cloud.githubusercontent.com/assets/11186313/12711099/ff950ec8-c8f7-11e5-892d-68bed8579109.png)
