### ISSUE TITLE
Footer: Titan Logo Resource Code rel="nofollow" must be implemented in Subpages only not in Home page.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Castleglen#42]
![image](https://cloud.githubusercontent.com/assets/11186313/12289354/068961ca-ba16-11e5-9764-3933190140b4.png)

**Comment by Santosh-titan** [comment]
Please elaborate this issue

**Comment by roseliesromeo** [comment]
Rel = "no follow" should only be implemented in the inner pages not in home page.
