### ISSUE TITLE
Product listing: Distorted grid layout.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Castleglen#49]
![image](https://cloud.githubusercontent.com/assets/11186313/12313959/85a0dbbe-baa7-11e5-862a-248c020030b9.png)

**Comment by roseliesromeo** [comment]
Not fixed in this page.
http://castleglen.stage.titanweb.com.au/product-category/cleaning-products/page/2/

**Comment by Santosh-titan** [comment]
Its Working fine for me. See screenshot
![product-page](https://cloud.githubusercontent.com/assets/13828562/12612246/491a92aa-c517-11e5-8854-8ddf0f1443d2.png)

**Comment by roseliesromeo** [comment]
Try to replicate in other PCs.  The issue is intermittent.  I am able to replicate in two PCs here while in other PCs, it looks fine.

**Comment by Santosh-titan** [comment]
Strange, I tested in all our systems,  I am unable to replicate this issue.

**Comment by roseliesromeo** [comment]
I am able to replicate in 2 ou tof 5 PCs.
