### ISSUE TITLE
News: It should up to 2 lines of post title.  Currently, only 1 line can be displayed.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Castleglen#55]
https://knowledgebase.titanweb.com.au/implementation/standard-pages/post-title-and-post-desription

**Comment by Santosh-titan** [comment]
Read second point In above url.
Exception will be if section for title strictly cannot fit 2 lines

**Comment by roseliesromeo** [comment]
That exception is not applicable to listing page.  That is intended for sections (ex lead-ins) where there is container.
