### ISSUE TITLE
Header: Icon will no longer display once category menu is removed and added back.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Castleglen#78]
![image](https://cloud.githubusercontent.com/assets/11186313/12771156/f11e5d84-ca61-11e5-864d-c9931762f338.png)

**Comment by Santosh-titan** [comment]
You have to add menu icons manually(normal icon and hover icon). See following screenshot
![cat-menu-icons](https://cloud.githubusercontent.com/assets/13828562/12774476/41398a1a-ca6b-11e5-834c-f805331a48d1.png)
